apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: prod
resources:
  - ../../base
  - namespace.yml
  - ingress.yml
images:
  - name: ghcr.io/toyonix/gitops-terraform-kubernates/backend
    newTag: prod
  - name: ghcr.io/toyonix/gitops-terraform-kubernates/frontend
    newTag: prod
